name: Build openSenseMap language package and publish

on:
  release:
    branches:
      - main
    types: [released]

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Archive language files
        uses: actions/upload-artifact@v2
        with:
          name: openSenseMap-i18n
          path: dist
      - name: Release new version
        # Get tag name and delete v so we get a SemVer compliant version
        run: |
          tag="${{ github.event.release.tag_name }}"
          npm publish --tag ${tag#v} --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
